### PR TITLE
docs: Add text to current example

### PR DESCRIPTION
**Pull request by apkrelling**
## Pull Request description

This PR adds some text to the current example, to make it easier for the reader to understand.

This PR attempts to solve issue #25 .

## Pull Request checklists

This PR is a:

- [ ] bug-fix
- [ ] new feature
- [x] maintenance

About this PR:

- [ ] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [x] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:

- [x] I have reviewed the changes and it contains no misspelling.
- [x] The code is well commented, especially in the parts that contain more
      complexity.
- [x] New and old tests passed locally.

## Reviewer's checklist

Copy and paste this template for your review's note:

```
## Reviewer's Checklist

- [ ] I confirm that the issues mentioned were fixed/resolved .
```

### CODE REVIEW

**Comment by apkrelling** [comment]
@xmnlab , please let me know if this helps.

**Comment by xmnlab** [comment]
@apkrelling , thanks for working on that.
in general, it looks good, but you need to rebase your branch on top of the upstream/main.
let me know if you need any help about that.

as you will see, now it would be necessary to declare the variable (VariableDeclaration) before use the variables.

**Comment by apkrelling** [comment]
@xmnlab , I updated this PR, rewriting the get started guide to match the style of the other tutorials, as well as adding some items you've requested. Hopefully it's better.

**Review by xmnlab — APPROVED** [review]
@apkrelling that looks great. thank you so much!

**Comment by xmnlab** [comment]
this change will be available online in the next release.
thank you so much for working on that. appreciate that.

**Pull request merged**
