### PR TITLE
feat: create ForRangeExpr class

### PR DESCRIPTION
**Pull request by apkrelling**
## Pull Request description

This PR adds ForRangeExpr and modifies ForRangeLoop. 
This PR is an attempt to solve #94   .

- [X] added new ASTKind
- [X] created ForRangeExpr class
- [X] modified ForRangeLoop class to be compatible with ForRangeExpr
- [X] updated `__init__.py` to include the new imports and classes in the `__all__` list
- [X] added the new classes visit methods in `transpilers/python.py`
- [X] added test in `tests/transpilers/test_python.py`
- [X] added test in `tests/test_flows.py`

## How to test these changes

```python
from astx.variables import Variable, InlineVariableDeclaration
from astx.blocks import Block
from astx.flows import ForRangeLoop, ForRangeExpr
from astx.datatypes import LiteralInt32
from astx.datatypes import Int32
from astx.modifiers import MutabilityKind

# Create a range expression from 0 to 6 with step 1
range_expr = ForRangeExpr(
    start=LiteralInt32(0),
    end=LiteralInt32(6),
    step=LiteralInt32(1)
)

# Variable declaration for the loop variable
loop_var = InlineVariableDeclaration(
    name="i",
    type_=Int32,
    mutability=MutabilityKind.mutable,
    value=LiteralInt32(1),
)
loop_var2 = Variable(name="i")

# Loop body
loop_body = Block(name="loop_body")

# Add statements to the loop body as needed
lit_2 = LiteralInt32(2)
basic_op = loop_var2 * lit_2
loop_body.append(basic_op)

# Create the ForRangeLoop using the range expression
for_loop = ForRangeLoop(
    variable=loop_var,
    range_expr=range_expr,
    body=loop_body,
)
```

## Pull Request checklists

This PR is a:

- [ ] bug-fix
- [X] new feature
- [ ] maintenance

About this PR:

- [ ] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [X] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:

- [ ] I have reviewed the changes and it contains no misspelling.
- [ ] The code is well commented, especially in the parts that contain more
      complexity.
- [ ] New and old tests passed locally.

## Reviewer's checklist

Copy and paste this template for your review's note:

```
## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [ ] I confirm that the issues mentioned were fixed/resolved .
```

### CODE REVIEW

**Comment by apkrelling** [comment]
The AST png and ascii representations for the code:
```python
from astx.variables import Variable, InlineVariableDeclaration
from astx.blocks import Block
from astx.flows import ForRangeLoop, ForRangeExpr
from astx.datatypes import LiteralInt32
from astx.datatypes import Int32
from astx.modifiers import MutabilityKind

# Create a range expression from 0 to 10 with step 1
range_expr = ForRangeExpr(
    start=LiteralInt32(0),
    end=LiteralInt32(6),
    step=LiteralInt32(1)
)

# Variable declaration for the loop variable
loop_var = InlineVariableDeclaration(
    name="i",
    type_=Int32,
    mutability=MutabilityKind.mutable,
    value=LiteralInt32(1),
)
loop_var2 = Variable(name="i")

# Loop body
loop_body = Block(name="loop_body")

# Add statements to the loop body as needed
lit_2 = LiteralInt32(2)
basic_op = loop_var2 * lit_2
loop_body.append(basic_op)

# Create the ForRangeLoop using the range expression
for_loop = ForRangeLoop(
    variable=loop_var,
    range_expr=range_expr,
    body=loop_body,
)
```
are:
for_range_loop_jupyterlab
for_range_loop_ipython
for_range_expr_ipython
for_range_expr_jupyterlab

**Comment by apkrelling** [comment]
For the transpiler:
```python
# Create a ForRangeExpr node
range_expr = astx.ForRangeExpr(
    start=astx.LiteralInt32(0), end=astx.LiteralInt32(10), step=astx.LiteralInt32(1)
)

# Initialize the generator
generator = astx2py.ASTxPythonTranspiler()

# Generate Python code
generated_code = generator.visit(range_expr)
generated_code
```

output: `range(0,10,1)`

**Comment by apkrelling** [comment]
Please note that on the [issue](https://github.com/arxlang/astx/issues/94) I put a comment mentioning that the output of the transpiler should be something like `result = [x * 2 for x in range(1,6)]`. However, this should be the output for the `ForRangeLoop` (which is a Stmt), and not for the `ForRangeExpr`.

**Comment by apkrelling** [comment]
@xmn, after our discussions, here is the update for this PR:

- [X] added new ASTKind
- [X] created ForRangeExpr class
- [X] got ForRangeLoop back to its original code
- [X] changed class names: ForRangeLoop -> ForRangeLoopStmt, ForRangeExpr -> ForRangeLoopExpr
- [X] updated `__init__.py` to include the new imports and classes in the `__all__` list
- [X] edited tests in `tests/test_flows.py`

**Comment by apkrelling** [comment]
A couple of things to discuss:
* in https://github.com/arxlang/astx/blob/main/docs/tutorials/for-loop.ipynb, in the second code cell, there's a ForRangeExpr used with a ForRangeLoop. 
* should we create an issue to add a transpiler method for ForRangeLoopStmt?
* for the transpiler method of ForRangeLoopExpr: should it still be something like `result = [x * 2 for x in range(1,6)]`?

**Comment by apkrelling** [comment]
Code used to test these changes:
```python
from astx.variables import Variable, InlineVariableDeclaration
from astx.blocks import Block
from astx.flows import ForRangeLoopExpr
from astx.datatypes import LiteralInt32
from astx.datatypes import Int32
from astx.modifiers import MutabilityKind
import astx
from astx.transpilers import python as astx2py

###-
# Variable declaration for the loop variable
loop_var = InlineVariableDeclaration(
    name="i",
    type_=Int32,
    mutability=MutabilityKind.mutable,
    value=LiteralInt32(1),
)

loop_var2 = Variable(name="i")

# Loop body
loop_body = Block(name="loop_body")

# Add statements to the loop body as needed
lit_2 = LiteralInt32(2)
basic_op = loop_var2 * lit_2
loop_body.append(basic_op)


# Create a range expression from 0 to 10 with step 1
for_expr = ForRangeLoopExpr(
    variable=loop_var,
    start=LiteralInt32(0),
    end=LiteralInt32(6),
    step=LiteralInt32(1),
    body=loop_body
)
for_expr

generator = astx2py.ASTxPythonTranspiler()
generated_code = generator.visit(for_expr)
print(generated_code)
```

**Comment by xmnlab** [comment]
thank you @apkrelling !
That looks good!

I am merging this PR, and I will play a bit with that and maybe open a follow-up PR with some small changes and I will fix the notebook as well.

thanks, and sorry for messing with the issue XD

**Pull request merged**
